

// Wish Tally Const
var WISH_TALLY_CHARACTER_EVENT_WISH_SHEET_NAME = "Character Event Wish History";
var WISH_TALLY_WEAPON_EVENT_WISH_SHEET_NAME = "Weapon Event Wish History";
var WISH_TALLY_PERMANENT_WISH_SHEET_NAME = "Permanent Wish History";
var WISH_TALLY_NOVICE_WISH_SHEET_NAME = "Novice Wish History";
var WISH_TALLY_SETTINGS_SHEET_NAME = "Settings";
var WISH_TALLY_DASHBOARD_SHEET_NAME = "Dashboard";
var WISH_TALLY_CHANGELOG_SHEET_NAME = "Changelog";
var WISH_TALLY_PITY_CHECKER_SHEET_NAME = "Pity Checker";
var WISH_TALLY_EVENTS_SHEET_NAME = "Events";
var WISH_TALLY_CHARACTERS_SHEET_NAME = "Characters";
var WISH_TALLY_WEAPONS_SHEET_NAME = "Weapons";
var WISH_TALLY_RESULTS_SHEET_NAME = "Results";
var WISH_TALLY_README_SHEET_NAME = "README";


// AutoHotkey Const
var AUTOHOTKEY_SHEET_NAME = "AutoHotkey";
var AUTOHOTKEY_SCRIPT_SHEET_NAME = "AutoHotkey-Script";